routes/web.php
<?php

use App\Http\Controllers\PostController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/info', function(){
    return view('phpinfo'); 
});
Route::get('/', function () {
    return view('welcome');
});
Route::get('/post/show',[PostController::class, 'show']);
Route::resource('post',PostController::class);

app/Models/Post.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
// use Illuminate\Database\Eloquent\Model;
use Jenssegers\Mongodb\Eloquent\Model ;
use Jenssegers\Mongodb\Eloquent\Model as Eloquent;

class Post extends Eloquent
{
    use HasFactory;
    protected $connection = 'mongodb';
    protected $fillable = ['title','username','content'];
}

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Models/car.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Jenssegers\Mongodb\Eloquent\Model as Eloquent;

class car extends Model
{
    use HasFactory;
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use App\Models\Post;
use Illuminate\Http\Request;
use App\Repositories\PostRepository;

class PostController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

    protected $PostRepository;
    public function __construct(PostRepository $postRepository)
    {
        $this->postRepository = $postRepository;
    }
    public function index()
    {
        // $data = Post::all();
        // return view('post.index',compact('data'));

        $data = $this->postRepository->getAll();
        return view('post.index',compact('data'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('post.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        // Post::create($request->all());
        // return redirect()->route('post.index') 
        // ->with('succcess', 'user create succcessfully');

        $data = $request->all();

        $post = $this->postRepository->create($data);
        return redirect()->route('post.index',compact('post'));  
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function show(Post $post)
    {

        // $post = $this->postRepository->find($post);
        $id = Post::has('id')->get();   
        dd($id);
        return view('post.show',compact('post'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function edit(Post $post)
    {
        return view('post.edit',compact('post'));
    }
    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Post $post)
    {
        // request()->validate([
        //     'title' => 'required',
        //     'username' => 'required',
        //     'content' => 'required',
        // ]);

        // $post->update($request->all());
        // return redirect()->route('post.index')
        // ->with('succcess', 'user update succcessfully');

        $data = $request->all();
        // dd($data);
        $post = $this->postRepository->update($post->_id, $data);
        return redirect()->route('post.index',compact('post'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Post  $post
     * @return \Illuminate\Http\Response
     */
    public function destroy(Post $post)
    {
        // $post->delete();
        // return redirect()->route('post.index')
        // ->with('succcess', 'user delete succcessfully');

        $this->postRepository->delete($post->_id);
        return redirect()->route('post.index');
    }
}

resources/views/phpinfo.blade.php
<?php
    phpinfo();
?>

resources/views/post/create.blade.php
@extends('post.layout')


@section('content')
<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <h2 class="col-xs-12 col-sm-12 col-md-12 text-center">Add New User</h2>
        </div>
    </div>
</div>
<form method="post" action="{{route('post.store')}}">
    @csrf
    <div class="form-group">
        <label for="title">Title:</label>
        <input type="text" class="form-control" id="title" name="title" placeholder="Title">
    </div>
    <div class="form-group">
        <label for="username">User name:</label>
        <input type="text" class="form-control" id="username" name="username" placeholder="Username">
    </div>
    <div class="form-group">
        <label for="content">Content:</label>
        <input type="text" class="form-control" id="content" name="content" placeholder="Content">
    </div >
    <div class="col-xs-12 col-sm-12 col-md-12 text-center">
        <button type="submit" class="btn btn-primary">Send</button>
        <a class="btn btn-primary" href="{{ route('post.index') }}"> Back </a>
    </div>
</form>

resources/views/post/edit.blade.php
@extends('post.layout')


@section('content')
<div class="row">
    <div class="col-lg-12 margin-tb">
        <div class="pull-left">
            <h2>Edit User</h2>
        </div>
    </div>
</div>

<form method="post" action="{{route('post.update',$post->_id)}}">
    @csrf
    @method('PUT')


    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Title:</strong>
                <input type="text" name="title" id="title" value="{{ $post->title }}" class="form-control" placeholder="Title">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>User name:</strong>
                <input type="text" class="form-control" value="{{ $post->username }}" id="username" name="username" placeholder="Username">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12">
            <div class="form-group">
                <strong>Content:</strong>
                <input type="text" class="form-control" value="{{ $post->content }}" id="content" name="content" placeholder="Content">
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12 text-center">
            <button type="submit" class="btn btn-primary">Submit</button>
            <a class="btn btn-primary" href="{{ route('post.index') }}"> Back</a>
        </div>
    </div>
</form>

resources/views/post/index.blade.php
@extends('post.layout')


@section('content')
<h3 style="text-align: center">All User</h3>
<table class="table">
    <thead>
        <tr>
            <th scope="col">No</th>
            <th scope="col">Title</th>
            <th scope="col">User name</th>
            <th scope="col">Content</th>
            <th scope="col">Status</th>
            <th>
                <div class="row">
                    <div class="col-lg-12 margin-tb">
                        <div class="pull-left">
                            <a class="btn btn-success" href="{{ route('post.create') }}"> Create New User</a>
                        </div>
                    </div>
                </div>
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach($data as $key=>$item)
        <tr>
            <th scope="row">{{$key}}</th>
            <td>{{$item->title}}</td>
            <td>{{$item->username}}</td>
            <td>{{$item->content}}</td>
            <td>
                <form method="post" action="{{route('post.destroy',$item)}} ">
                    <a class="btn btn-info" href="{{route('post.show',$item)}}"> Show</a>
                    <a class="btn btn-primary" href="{{route('post.edit',$item)}}">Edit</a>
                    @csrf
                    @method('DELETE')
                    <button type="submit" method="DELETE" class="btn btn-danger">Delete</button>
                </form>
            </td>
            <td></td>
        </tr>
        @endforeach
    </tbody>
</table>

resources/views/post/layout.blade.php
<!DOCTYPE html>
<html>
<head>
	<title></title>
	<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</head>
<body>


<div class="container">
    @yield('content')
</div>


</body>
</html>

resources/views/post/show.blade.php
@extends('post.layout')


@section('content')
    <div class="row">
        <div class="col-lg-12 margin-tb">
            <div class="pull-left">
                <h2 class="col-xs-12 col-sm-12 col-md-12 text-center"> Show User</h2>
            </div>
        </div>
    </div>
    <form method="post" action="{{route('post.update',$post->_id)}}">
    @csrf
    @method('GET')
    <div class="row">
        <div class="col-xs-12 col-sm-12 col-md-12 text-center">
            <div class="form-group">
                <strong>Title:</strong>
                {{ $post->title }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12 text-center">
            <div class="form-group">
                <strong>User name:</strong>
                {{ $post->username }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12 text-center">
            <div class="form-group">
                <strong>Content:</strong>
                {{ $post->content }}
            </div>
        </div>
        <div class="col-xs-12 col-sm-12 col-md-12 text-center">
            <a class="btn btn-primary" href="{{ route('post.index') }}"> Back</a>
        </div>
    </div>
    </form>
@endsection